backend:
  name: github
  repo: Sharma-Rajat/aremm-comingSoon # Path to your Github repository
  branch: master # Branch to update
  media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
  public_folder: "public/img" # The src attribute for uploaded media will begin with /images/uploads